# -*- coding: utf-8 -*-
"""level2_smartcity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/127Cf1LPv55lH5ZjlUe0WGqxhxsRF1RdE
"""

def classical_priority_mux(s3, s2, s1, s0):

    if s0 == 1:
        return "Medical Emergency (Highest Priority)"
    elif s3 == 1:
        return "Fire Detected"
    elif s2 == 1:
        return "Gas Leakage"
    elif s1 == 1:
        return "Intrusion"
    else:
        return "No Signal"


print(f"Classical Output: {classical_priority_mux(1, 0, 1, 0)}")

import ipywidgets as widgets
from IPython.display import display

# Redefine the classical priority mux function for use in the interactive board
def classical_priority_mux(s3, s2, s1, s0):
    if s0 == 1:
        return "Medical Emergency (Highest Priority)"
    elif s3 == 1:
        return "Fire Detected"
    elif s2 == 1:
        return "Gas Leakage"
    elif s1 == 1:
        return "Intrusion"
    else:
        return "No Signal"

"""### Interactive Classical Priority Multiplexer

Adjust the sliders below to set the input signals (0 or 1) and see the prioritized output.
"""

# quantum implementation
!pip install qiskit qiskit-aer

import ipywidgets as widgets
from IPython.display import display

# The classical priority mux function has already been defined and modified for highest priority Medical Emergency.
# We will use the existing function.

# Create sliders for each input
s0_slider = widgets.IntSlider(min=0, max=1, step=1, description='s0 (Medical):', orientation='horizontal')
s1_slider = widgets.IntSlider(min=0, max=1, step=1, description='s1 (Intrusion):', orientation='horizontal')
s2_slider = widgets.IntSlider(min=0, max=1, step=1, description='s2 (Gas):', orientation='horizontal')
s3_slider = widgets.IntSlider(min=0, max=1, step=1, description='s3 (Fire):', orientation='horizontal')

# Create an output widget to display the result
output_widget = widgets.Output()

# Define a function to update the output based on slider values
def update_output(change):
    with output_widget:
        output_widget.clear_output()
        s0 = s0_slider.value
        s1 = s1_slider.value
        s2 = s2_slider.value
        s3 = s3_slider.value
        result = classical_priority_mux(s3, s2, s1, s0)
        print(f"Input: s3={s3}, s2={s2}, s1={s1}, s0={s0} | Output: {result}")

# Link sliders to the update function
s0_slider.observe(update_output, names='value')
s1_slider.observe(update_output, names='value')
s2_slider.observe(update_output, names='value')
s3_slider.observe(update_output, names='value')

# Display the widgets
display(s0_slider, s1_slider, s2_slider, s3_slider, output_widget)

# Initial call to display the default output
update_output(None)

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

from qiskit import QuantumCircuit
from qiskit_aer import Aer
from qiskit.quantum_info import Statevector
from IPython.display import display

# Qubits:
# q0 = Medical (s0) - Now Highest Priority
# q1 = Intruder (s1)
# q2 = Gas (s2)
# q3 = Fire (s3)
# q4 = Output (mux output)


qc = QuantumCircuit(5, 1) # 5 qubits, 1 classical bit for measurement of q4

qc.h([0,1,2,3])

qc.barrier()

# ---- PRIORITY LOGIC (Medical Emergency (q0) is now highest priority) ----

# Medical (q0) → output (q4) = 1
qc.cx(0, 4)

# Fire (q3) → only if Medical (q0) = 0
qc.x(0)
qc.ccx(0, 3, 4)
qc.x(0)

# Gas (q2) → only if Medical=0 AND Fire=0
qc.x(0)
qc.x(3)
qc.mcx([0, 3, 2], 4)
qc.x(3)
qc.x(0)

# Intruder (q1) → only if Medical=0 AND Fire=0 AND Gas=0
qc.x([0, 3, 2])
qc.mcx([0, 3, 2, 1], 4)
qc.x([0, 3, 2])

qc.barrier()


qc.measure(4, 0)


backend = Aer.get_backend('qasm_simulator')
job = backend.run(qc, shots=1024)
result = job.result()
counts = result.get_counts(qc)

# ---- STATEVECTOR ----

qc_for_sv = QuantumCircuit(5)


qc_for_sv.h([0,1,2,3])
qc_for_sv.barrier()

# Medical (q0) → output (q4) = 1
qc_for_sv.cx(0, 4)

# Fire (q3) → only if Medical (q0) = 0
qc_for_sv.x(0)
qc_for_sv.ccx(0, 3, 4)
qc_for_sv.x(0)

# Gas (q2) → only if Medical=0 AND Fire=0
qc_for_sv.x(0)
qc_for_sv.x(3)
qc_for_sv.mcx([0, 3, 2], 4)
qc_for_sv.x(3)
qc_for_sv.x(0)

# Intruder (q1) → only if Medical=0 AND Fire=0 AND Gas=0
qc_for_sv.x([0, 3, 2])
qc_for_sv.mcx([0, 3, 2, 1], 4)
qc_for_sv.x([0, 3, 2])

qc_for_sv.barrier()

sv = Statevector.from_instruction(qc_for_sv)
print(sv)
print(f"Counts for output qubit q4 (0 or 1): {counts}")

from qiskit.visualization import plot_histogram
from IPython.display import display

fig = plot_histogram(counts, title="Priority MUX Output")
display(fig)

from qiskit import QuantumCircuit
from qiskit_aer import Aer

backend = Aer.get_backend('qasm_simulator')

def run_case(s0, s1, s2, s3):
    qc = QuantumCircuit(5,1)


    if s0: qc.x(0) # Medical
    if s1: qc.x(1) # Intruder
    if s2: qc.x(2) # Gas
    if s3: qc.x(3) # Fire

    # Medical (q0) → output (q4) = 1
    qc.cx(0, 4)

    # Fire (q3) → only if Medical (q0) = 0
    qc.x(0)
    qc.ccx(0, 3, 4)
    qc.x(0)

    # Gas (q2) → only if Medical=0 AND Fire=0
    qc.x(0)
    qc.x(3)
    qc.mcx([0, 3, 2], 4)
    qc.x(3)
    qc.x(0)

    # Intruder (q1) → only if Medical=0 AND Fire=0 AND Gas=0
    qc.x([0, 3, 2])
    qc.mcx([0, 3, 2, 1], 4)
    qc.x([0, 3, 2])

    qc.measure(4,0)

    result = backend.run(qc, shots=1).result()
    return list(result.get_counts().keys())[0]

print("S3 S2 S1 S0 | Output")
print("--------------------")

for i in range(16):
    s0 = (i>>0)&1
    s1 = (i>>1)&1
    s2 = (i>>2)&1
    s3 = (i>>3)&1

    out = run_case(s0,s1,s2,s3)
    print(f"{s3}  {s2}  {s1}  {s0}  |   {out}")

# Calculate and display the percentage of correctness
total_shots = 1024
observed_zeros = counts.get('0', 0)
observed_ones = counts.get('1', 0)

# Ideal probabilistic distribution for a 4-input MUX in superposition
# 15 out of 16 input states should result in a '1' output
# 1 out of 16 input states should result in a '0' output (only for 0000 input)
expected_zeros = (1/16) * total_shots
expected_ones = (15/16) * total_shots

# Calculate accuracy based on deviation from expected counts
deviation_zeros = abs(observed_zeros - expected_zeros)
deviation_ones = abs(observed_ones - expected_ones)

total_deviation = deviation_zeros + deviation_ones
accuracy = ((total_shots - total_deviation) / total_shots) * 100

print(f"Total Shots: {total_shots}")
print(f"Observed '0' Counts: {observed_zeros} (Expected: {expected_zeros})")
print(f"Observed '1' Counts: {observed_ones} (Expected: {expected_ones})")
print(f"Deviation for '0': {deviation_zeros}")
print(f"Deviation for '1': {deviation_ones}")
print(f"Total Deviation from Ideal: {total_deviation}")
print(f"Accuracy of Probabilistic Output: {accuracy:.2f}%")

print("\nNote: The `run_case` function in a previous cell (`bksudE0gr9ia`) deterministically verifies the classical logic of your quantum circuit for each specific input combination, confirming its functional correctness.")

