# -*- coding: utf-8 -*-
"""level3_hadamard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-DEUuONdwxgP5LVrVlxbwKKwN-11_Ee6
"""

!pip install qutip

import numpy as np
from qutip import basis, Bloch, sigmax, sigmay, sigmaz


# Define basis states

zero = basis(2, 0)
one = basis(2, 1)


# Define given states

psi1 = (zero + one).unit()   # |ψ1> = |+>
psi2 = (zero - one).unit()   # |ψ2> = |->

print("State |ψ1> =")
print(psi1)

print("\nState |ψ2> =")
print(psi2)


# VERIFICATION (Inner Product)

overlap = psi1.dag() * psi2   # NO indexing needed

print("\nInner product <ψ1|ψ2> =", overlap)

if np.isclose(overlap, 0):
    print("✅ VERIFIED: States are orthogonal → NOT the same")
else:
    print("❌ States are not orthogonal")


# BLOCH COORDINATES (Expectation values)

x1 = (psi1.dag() * sigmax() * psi1).real
y1 = (psi1.dag() * sigmay() * psi1).real
z1 = (psi1.dag() * sigmaz() * psi1).real

x2 = (psi2.dag() * sigmax() * psi2).real
y2 = (psi2.dag() * sigmay() * psi2).real
z2 = (psi2.dag() * sigmaz() * psi2).real

print("\nBloch Coordinates:")
print(f"|ψ1> → ({x1:.2f}, {y1:.2f}, {z1:.2f})")
print(f"|ψ2> → ({x2:.2f}, {y2:.2f}, {z2:.2f})")

# VISUALIZATION (Bloch Sphere)

b = Bloch()

b.add_states(psi1)
b.add_states(psi2)

b.vector_color = ['r', 'b']  # red = ψ1, blue = ψ2

b.show()


# EXPLANATION (Printed)

print("\nExplanation:")
print("Both states lie on the equator of the Bloch sphere (z = 0).")
print("ψ1 points along +X axis, while ψ2 points along -X axis.")
print("They differ by a relative phase of π and are orthogonal.")
print("Hence, they are NOT similar states.")